sudo: false
language: node_js
services:
  - rabbitmq

cache:
  directories:
    - node_modules

node_js:
  - '10'
  - '9'
  - '8'

branches:
 except:
   - /^v\d+\.\d+\.\d+$/

before_script:
  - npm prune
script:
  - npm run flow:check
  - npm run test:cover
  - npm run build
  - npm run lint
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      npm run report-coverage;
      ./node_modules/.bin/travis-deploy-once && npm run semantic-release;
    fi
